### ISSUE TITLE
Update NextJS comment for Vanilla Extract

### ISSUE THREAD

**Issue by willbattel** [andreipfeiffer/css-in-js#22]
It seems that the remarks about NextJS might be out of date (https://github.com/andreipfeiffer/css-in-js/blob/main/README.md#worth-mentioning-observations-10)

Vanilla Extract now offers an official plugin for NextJS. I'm not 100% certain about its efficacy but it looks to at the very least provide official support)

https://vanilla-extract.style/documentation/integrations/next/

**Comment by andreipfeiffer** [comment]
You're right, thanks for pointing it out. I've updated it.

**Comment by willbattel** [comment]
@andreipfeiffer just a heads up it looks like that commit might include an accidental change that broke the formatting of the Overview table.

**Comment by andreipfeiffer** [comment]
Pfff, thank you so much for catching that @willbattel 🤘
It would have probably taken me quite some time to spot it 🥹

**Comment by willbattel** [comment]
Haha no worries, appreciate the repo!
