### ISSUE TITLE
Question - dynamic styles from DB in SSR or React Server Components

### ISSUE THREAD

**Issue by lveillard** [andreipfeiffer/css-in-js#24]
Hello! Great research. After reading this research I think you might be able to solve our weird use case!

We store our styles in the database and we use nextjs. I'm looking for something that could run the fetch in the server side and inyect the styles with automatic hydration. 

Using runtime librarie like twind or the runtime version of unoCss kinda works, but generates extra loading time as everything is done in the client side.

Thanks!

**Comment by andreipfeiffer** [comment]
Hi @lveillard ,
Well, just thinking out loud here, I guess no library cares where do the styles come from when you render on the server, right? They could be statically defined in a JS object, or fetched from a DB, they don't really care in this regard. The only exception here is **vanilla-extract**, which requires you to statically define styles in special separate files.

So, static CSS extraction I don't think will work here, therefore you probably need a runtime solution. The smallest runtime css-in-js library is probably [goober](https://goober.js.org/). I somewhat know the maintainer, but not sure the maintenance status of the lib.

Now, you mentioned `twind` and `unoCss` which both use Atomic CSS. You might also want to checkout [Compiled](https://compiledcssinjs.com/docs/) from Atlassian, which also has a reduced size but many features which might work for you.

**Comment by lveillard** [comment]
Thanks! Goober looks great but maybe not maintained :S

Compiled looks like a good match as well. I just need to check if it is possible to have the styled constants as async items that await for the right props from the database. Lets hope it's a yes. 

Thanks again for the suggestion

**Comment by lveillard** [comment]
Now i remember that something that confused me about compiled is this page in the docs:

https://compiledcssinjs.com/docs/limitations

Which says runtime styles don't work. But somehow this example does

https://stackblitz.com/edit/nextjs-flhtjd?file=src%2Fpages%2Findex.js

**Comment by andreipfeiffer** [comment]
The limitation described there illustrates a **dynamic selector**, not a **dynamic value** for a static CSS property.
